-- MySQL Script generated by MySQL Workbench
-- Sat Nov 19 17:28:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TestSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TestSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TestSystem` DEFAULT CHARACTER SET utf8 ;
USE `TestSystem` ;

-- -----------------------------------------------------
-- Table `TestSystem`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestSystem`.`teacher` (
  `idteacher` INT NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `experience` INT NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idteacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TestSystem`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestSystem`.`class` (
  `idclassClass` INT NOT NULL AUTO_INCREMENT,
  `classname` VARCHAR(45) NOT NULL,
  `idteacherClass` INT NOT NULL,
  PRIMARY KEY (`idclassClass`),
  UNIQUE INDEX `classname_UNIQUE` (`classname` ASC) VISIBLE,
  UNIQUE INDEX `idteacherClass_UNIQUE` (`idteacherClass` ASC) VISIBLE,
  CONSTRAINT `idteacherClass`
    FOREIGN KEY (`idteacherClass`)
    REFERENCES `TestSystem`.`teacher` (`idteacher`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TestSystem`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestSystem`.`student` (
  `idstudent` INT NOT NULL,
  `idclassStudent` INT NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstudent`),
  INDEX `idclass_idx` (`idclassStudent` ASC) VISIBLE,
  CONSTRAINT `idclassStudent`
    FOREIGN KEY (`idclassStudent`)
    REFERENCES `TestSystem`.`class` (`idclassClass`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TestSystem`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestSystem`.`subject` (
  `idsubject` INT NOT NULL AUTO_INCREMENT,
  `subjectname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsubject`),
  UNIQUE INDEX `subjectname_UNIQUE` (`subjectname` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TestSystem`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestSystem`.`topic` (
  `idtopic` INT NOT NULL AUTO_INCREMENT,
  `topicname` VARCHAR(45) NOT NULL,
  `idsubject` INT NOT NULL,
  INDEX `idsubject_idx` (`idsubject` ASC) VISIBLE,
  PRIMARY KEY (`idtopic`),
  UNIQUE INDEX `topicname_UNIQUE` (`topicname` ASC) VISIBLE,
  CONSTRAINT `idsubject`
    FOREIGN KEY (`idsubject`)
    REFERENCES `TestSystem`.`subject` (`idsubject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TestSystem`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestSystem`.`test` (
  `idtest` INT NOT NULL,
  `idtopic` INT NOT NULL,
  PRIMARY KEY (`idtest`),
  INDEX `idtopic_idx` (`idtopic` ASC) VISIBLE,
  CONSTRAINT `idtopic`
    FOREIGN KEY (`idtopic`)
    REFERENCES `TestSystem`.`topic` (`idtopic`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TestSystem`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestSystem`.`result` (
  `idstudent` INT NOT NULL,
  `idtestResult` INT NOT NULL,
  `mark` INT NOT NULL,
  `day` DATE NOT NULL,
  `numcorans` INT NULL,
  INDEX `idstudent_idx` (`idstudent` ASC) VISIBLE,
  INDEX `idtest_idx` (`idtestResult` ASC) VISIBLE,
  PRIMARY KEY (`idstudent`, `idtestResult`),
  CONSTRAINT `idstudent`
    FOREIGN KEY (`idstudent`)
    REFERENCES `TestSystem`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idtestResult`
    FOREIGN KEY (`idtestResult`)
    REFERENCES `TestSystem`.`test` (`idtest`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TestSystem`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestSystem`.`question` (
  `idquestion` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(100) NOT NULL,
  `questionans1` VARCHAR(100) NOT NULL,
  `questionans2` VARCHAR(100) NOT NULL,
  `questionans3` VARCHAR(100) NOT NULL,
  `questionans4` VARCHAR(100) NOT NULL,
  `corans` VARCHAR(100) NOT NULL,
  `idtestQuest` INT NOT NULL,
  PRIMARY KEY (`idquestion`),
  INDEX `idtest_idx` (`idtestQuest` ASC) VISIBLE,
  CONSTRAINT `idtestQuest`
    FOREIGN KEY (`idtestQuest`)
    REFERENCES `TestSystem`.`test` (`idtest`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TestSystem`.`studyload`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestSystem`.`studyload` (
  `idteacher` INT NOT NULL,
  `idclassLoad` INT NOT NULL,
  `idsubject` INT NOT NULL,
  INDEX `idteacher_idx` (`idteacher` ASC) VISIBLE,
  INDEX `idclass_idx` (`idclassLoad` ASC) VISIBLE,
  INDEX `idsubject_idx` (`idsubject` ASC) VISIBLE,
  PRIMARY KEY (`idsubject`, `idclassLoad`, `idteacher`),
  CONSTRAINT `idteacher`
    FOREIGN KEY (`idteacher`)
    REFERENCES `TestSystem`.`teacher` (`idteacher`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idclassLoad`
    FOREIGN KEY (`idclassLoad`)
    REFERENCES `TestSystem`.`class` (`idclassClass`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idsubjectLoad`
    FOREIGN KEY (`idsubject`)
    REFERENCES `TestSystem`.`subject` (`idsubject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
